version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt  # This file will store dependencies

sphinx:
  configuration: docs/conf.py  # The Sphinx config file path

formats:
  - html
  - pdf
  - epub
